import * as PATHS from './constants';
import { SharedCorePathsType } from './types';

const PATHS_CONFIG = {
  FINANCES_API: PATHS.FINANCES_API_PATH,
  GOALS_API: PATHS.GOALS_API_PATH,
  USER_API: PATHS.USER_API_PATH,
  COURSE_API: PATHS.COURSE_API_PATH,
  COURSES_API: PATHS.COURSES_API_PATH,
  STUDENT_API: PATHS.STUDENT_API_PATH,
  STUDENTS_API: PATHS.STUDENTS_API_PATH,
  CLASS_ROOM_API: PATHS.CLASS_ROOM_API_PATH,
  PUBLIC: {
    ROOT: PATHS.PUBLIC_PATH,
    ASSETS: {
      ROOT: PATHS.PUBLIC_ASSETS_PATH,
      IMAGES: PATHS.PUBLIC_IMAGES_PATH,
    },
  },
};

export const getPaths = (): SharedCorePathsType => PATHS_CONFIG;
